version: '2.29.1'
services:
  car_shop_db:
    restart: always
    image: postgres:alpine3.19
    environment:
      - POSTGRES_DB=cottonpads
      - POSTGRES_USER=daniilmolchanov
      - POSTGRES_PASSWORD=microcuts1928
    ports:
      - "5450:5432"