spring:
  main:
    banner-mode: off
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/cottonpads
    username: daniilmolchanov
    password: microcuts1928
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: false
        temp:
          use_jdbc_metadata_defaults: false
    open-in-view: false
    http:
      multipart:
        enable: false
  liquibase:
    change-log: ./src/main/java/resource/db/changelog/changelog-master.yaml
port:
  9000
