spring:
  main:
    banner-mode: off
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5450/cottonpads
    username: daniilmolchanov
    password: microcuts1928
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        ddl-auto: create-drop
        default_schema: car_shop_schema
        temp:
          use_jdbc_metadata_defaults: false
    open-in-view: false
    http:
      multipart:
        enable: false
  liquibase:
    change-log: /db/changelog/changelog-master.yaml
