CREATE SCHEMA IF NOT EXISTS car_shop_schema;

CREATE TABLE IF NOT EXISTS car_shop_schema.users (
        id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        username VARCHAR(50),
        password TEXT,
        role VARCHAR(10)
        );

CREATE TABLE IF NOT EXISTS car_shop_schema.cars (
        id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        brand VARCHAR(100),
        model VARCHAR(100),
        year VARCHAR(4),
        price TEXT,
        condition TEXT
        );

CREATE TABLE IF NOT EXISTS car_shop_schema.orders (
        id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

        user_id INT UNIQUE,

        car_id INT UNIQUE,

         FOREIGN KEY (user_id) REFERENCES car_shop_schema.users(id)
         ON DELETE CASCADE
         ON UPDATE CASCADE,

         FOREIGN KEY (car_id) REFERENCES car_shop_schema.cars(id)
         ON DELETE CASCADE
         ON UPDATE CASCADE,

         status TEXT
         );
