CREATE TABLE IF NOT EXISTS users (
        id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        username VARCHAR(50),
        password TEXT,
        role VARCHAR(10)
        );

CREATE TABLE IF NOT EXISTS cars (
        id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        brand VARCHAR(100),
        model VARCHAR(100),
        year VARCHAR(4),
        price TEXT,
        condition TEXT
        );

CREATE TABLE IF NOT EXISTS orders (
        id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

        user_id INT UNIQUE,

        car_id INT UNIQUE,

         FOREIGN KEY (user_id) REFERENCES users(id)
         ON DELETE CASCADE
         ON UPDATE CASCADE,

         FOREIGN KEY (car_id) REFERENCES cars(id)
         ON DELETE CASCADE
         ON UPDATE CASCADE,

         status TEXT
         );

INSERT INTO cars(brand, model, year, price, condition)  VALUES
('AUDI', 'AUDO Q8', '2010', '1234567', 'GOOD'),
('BMV', 'X6', '2018', '5234568', 'BAD');
